### ISSUE TITLE
暂停同步预览或定时同步的功能

### ISSUE THREAD

**Issue by DeiDeiDei** [Trebor-Huang/vscode-btex#25]
Preview的同步显示有的时候很卡，字数比较多时会出现打一个字符预览都会卡的情况，但有时候又需要预览已有内容，可否增加关闭预览同步显示或设置间隔一段时间同步的选项

**Comment by Trebor-Huang** [comment]
但是预览从来都没有同步显示的功能啊

**Comment by Trebor-Huang** [comment]
你是否开了自动保存? 只有保存的时候才会预览.

而且就算这么做了, 预览更新的时间不会变快: 如果加载一次预览需要 5s, 那么保存一次, 经过 1s 后再保存, 预览会直接在 6s 处出现, 而不需要等到 10s.

**Comment by Trebor-Huang** [comment]
> 但有时候又需要预览已有内容

你的意思是开始预览的时候已有内容会消失? 能不能录个视频看一下, 这应该不可能发生的

**Comment by Trebor-Huang** [comment]
没有进一步反馈，暂时关闭
